name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "checkout repository"
          uses: "actions/checkout@v2"
        - name: "setup jdk"
          uses: "actions/setup-java@v2"
          with:
            distribution: openjdk
            java-version: 17
        - name: "setup gradle"
          uses: "gradle/gradle-build-action@v2"
        - name: "execute gradle build"
          run: ./gradlew build
        - name: "publish"
          if: "${{ runner.os == 'Linux' && env.STATUS != 'release' && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main/') }}"
          run: "./gradlew publish"
          env:
             ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
             ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"